### PR TITLE
[NUITizenGallery] Add samples for NUI components test.

### PR DESCRIPTION
**Pull request by AchoWang**
Add samples to test nui components.

### CODE REVIEW

**Review by huayongxu — APPROVED** [review]
lgtm

**Review by wb0716 — APPROVED** [review]
Good for me

**Review by zhouleonlei — APPROVED** [review]
lgtm

**Review by xiaowei-guan — APPROVED** [review]
LGTM

**Review by zg2nets — APPROVED** [review]
lgtm

**Comment by xuelian-bai** [comment]
looks good to me

**Review by dongsug-song — APPROVED** [review]
approved

**Review by AdunFang — COMMENTED** [review]
It is OK.

**Pull request merged**
