### PR TITLE
Add family board & photo slide samples from DA FH.

### PR DESCRIPTION
**Pull request by huayongxu**
This patch is migrate family board and photo silde samples from DA FH.

### CODE REVIEW

**Review by zg2nets — COMMENTED** [review]
Please verify the sample on tizen7.0 binary

**Comment by huayongxu** [comment]
> 

Done.

**Comment by huayongxu** [comment]
> 



> binary

Done.

**Comment by huayongxu** [comment]
> Please verify the sample on tizen7.0 binary

Done.

**Review by dongsug-song — APPROVED** [review]
approved

**Pull request merged**
