### PR TITLE
[NUITizenGallery] Fix remove vertical text cannot work issue of ScrollViewTest6.

### PR DESCRIPTION
**Pull request by AchoWang**
…lViewTest6.

### CODE REVIEW

**Comment by xuelian-bai** [comment]
looks good to me

**Review by wb0716 — APPROVED** [review]
Good for me

**Review by zg2nets — APPROVED** [review]
looks good~

**Review by AdunFang — APPROVED** [review]
It is OK.

**Review by elishateng — APPROVED** [review]
LGTM

**Review by huayongxu — APPROVED** [review]
lgtm

**Pull request merged**
