### PR TITLE
Fix XamlParseException of ImageButtonTest

### PR DESCRIPTION
**Pull request by AchoWang**
Issue:
ImageButtonTestPage show nothing.

Solution:
Because property "Icon" is not assignable, so assign proprety "Icon" in C# code.

### CODE REVIEW

**Review by wb0716 — APPROVED** [review]
Good for me

**Review by huayongxu — APPROVED** [review]
lgtm

**Review by zhouleonlei — APPROVED** [review]
lgtm

**Review by AdunFang — APPROVED** [review]
It is OK.

**Review by zg2nets — APPROVED** [review]
looks good~

**Review by elishateng — APPROVED** [review]
LGTM

**Review by zhouleonlei — APPROVED** [review]
lgtm

**Pull request merged**
