### PR TITLE
[NUITizenGallery] Add some properties for Slider and TabContent to make easier to add aurum TCs.

### PR DESCRIPTION
**Pull request by AchoWang**

### CODE REVIEW

**Comment by xuelian-bai** [comment]
looks good to me

**Review by huayongxu — APPROVED** [review]
lgtm

**Review by wb0716 — APPROVED** [review]
Good for me

**Review by zhouleonlei — APPROVED** [review]
lgtm

**Review by zg2nets — APPROVED** [review]
lgtm

**Review by elishateng — APPROVED** [review]
LGTM

**Review by everLEEst — APPROVED** [review]
Looks okay to me. but need to check few size changes..

**Pull request merged**
