### PR TITLE
[NUITizenGallery] Fix OnBtnDefaultButtonClicked does not take effect issue of BackgroundColorTest4.

### PR DESCRIPTION
**Pull request by AchoWang**

### CODE REVIEW

**Comment by xuelian-bai** [comment]
looks good to me

**Review by wb0716 — APPROVED** [review]

**Review by huayongxu — APPROVED** [review]
lgtm

**Review by AdunFang — APPROVED** [review]
It is OK.

**Review by elishateng — APPROVED** [review]
LGTM

**Pull request merged**
